# This is a basic workflow to help you get started with Actions

name: Java-Release-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #set up java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      #build stuff 
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: ./lib/
          wrapper-directory: ./lib/gradle/wrapper
          arguments: jar
        
      #upload-artifact-as-is 
      # our jars are named properly with version, so just upload those
      - uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: lib/build/libs/*.jar
